{ @author: Sylvain Maltais (support@gladir.com)
  @created: 2022
  @website(https://www.gladir.com/corail)
  @abstract(Target: Turbo Pascal, Free Pascal)
}

Program FALSE;

BEGIN
 If(ParamStr(1)='/?')or(ParamStr(1)='--help')or(ParamStr(1)='-h')or
   (ParamStr(1)='/h')or(ParamStr(1)='/H')Then Begin
  WriteLn('FALSE : Cette commande permet de retourner faux.');
  WriteLn;
  WriteLn('Syntaxe : FALSE');
 End
  Else
 Begin
  Halt(1);
 End;
END.