{ @author: Sylvain Maltais (support@gladir.com)
  @created: 2022
  @website(https://www.gladir.com/corail)
  @abstract(Target: Turbo Pascal, Free Pascal)
}

Program TRUE;

BEGIN
 If(ParamStr(1)='/?')or(ParamStr(1)='--help')or(ParamStr(1)='-h')or
   (ParamStr(1)='/h')or(ParamStr(1)='/H')Then Begin
  WriteLn('TRUE : Cette commande permet de retourner vrai.');
  WriteLn;
  WriteLn('Syntaxe : TRUE');
 End
  Else
 Begin
  Halt(0);
 End;
END.
